# borrowed from https://github.com/simonw/ca-fires-history/blob/main/.github/workflows/scrape.yml

name: Scrape latest data of MOON

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '15 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data of MOON
      run: |-
        mkdir -p moon
        cd moon
        curl http://files.direxionfunds.com/DirexionWebsiteFiles/holdings_moon.csv | python3 ../lintcsv.py > moon_holdings.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "[MOON] Latest data: ${timestamp}" || exit 0
        git push
